module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow'
]

module.exports.imageUrls = [
    'https://res.cloudinary.com/project-storage/image/upload/v1632837916/YelpCamp/digital-sennin-QttaHHgHz_w-unsplash_jmxw7e.jpg',
    'https://res.cloudinary.com/project-storage/image/upload/v1632837913/YelpCamp/eila-lifflander-wKNU7i6GGbY-unsplash_dnhpws.jpg',
    'https://res.cloudinary.com/project-storage/image/upload/v1632837553/YelpCamp/d-ng-nguy-n-tZ1i5tMLR30-unsplash_x8bapp.jpg',
    'https://res.cloudinary.com/project-storage/image/upload/v1632837548/YelpCamp/minh-tr-n-yhXOvO4WNLo-unsplash_effojl.jpg',
    'https://res.cloudinary.com/project-storage/image/upload/v1632837543/YelpCamp/markus-winkler-GGv2lpcaP0s-unsplash_ind1my.jpg',
    'https://res.cloudinary.com/project-storage/image/upload/v1632837544/YelpCamp/thai-an-ejP_nnf0rYU-unsplash_mhlfsl.jpg',
    'https://res.cloudinary.com/project-storage/image/upload/v1632837540/YelpCamp/my-nguyen-_Urhnvu18yk-unsplash_pl382h.jpg',
    'https://res.cloudinary.com/project-storage/image/upload/v1632837540/YelpCamp/soo-ann-woon-SgWcfBA1Be8-unsplash_w9q6ow.jpg',
    'https://res.cloudinary.com/project-storage/image/upload/v1632837540/YelpCamp/cristian-guerrero-B1UtwAqpdZM-unsplash_trlz0q.jpg',
    'https://res.cloudinary.com/project-storage/image/upload/v1632837537/YelpCamp/jeremy-bishop-GIpGxe2_cT4-unsplash_bwgxgp.jpg',
    'https://res.cloudinary.com/project-storage/image/upload/v1632837536/YelpCamp/christian-joudrey-DuD5D3lWC3c-unsplash_sci23t.jpg',
    'https://res.cloudinary.com/project-storage/image/upload/v1632837536/YelpCamp/markus-winkler-oIJj_ebUIKs-unsplash_fwck3q.jpg',
    'https://res.cloudinary.com/project-storage/image/upload/v1632837533/YelpCamp/dac-duy-pWGzENxa7LU-unsplash_c8gnip.jpg',
    'https://res.cloudinary.com/project-storage/image/upload/v1632837530/YelpCamp/jeremy-bishop-KXqHt7h6ESQ-unsplash_jn3ncg.jpg',
    'https://res.cloudinary.com/project-storage/image/upload/v1632837528/YelpCamp/martin-zangerl-yOuhjExBNXg-unsplash_jbfaqt.jpg',
    'https://res.cloudinary.com/project-storage/image/upload/v1632837526/YelpCamp/drew-farwell-ylQo5HSQPPg-unsplash_ysc6li.jpg',
    'https://res.cloudinary.com/project-storage/image/upload/v1632837526/YelpCamp/david-henrichs-OKBb9_v-K1I-unsplash_j51opg.jpg',
    'https://res.cloudinary.com/project-storage/image/upload/v1631787307/YelpCamp/oyhucjr0ajopr5yg9df2.jpg',
    'https://res.cloudinary.com/project-storage/image/upload/v1631722938/YelpCamp/rij3143yt1pjomwyylsh.jpg',
    'https://res.cloudinary.com/project-storage/image/upload/v1631722935/YelpCamp/glj4c8lgpn0zfyiknndn.jpg',
    'https://res.cloudinary.com/project-storage/image/upload/v1632841156/YelpCamp/kazuend-cCthPLHmrzI-unsplash_poj8ew.jpg'
]

module.exports.reviews = [
    "one of my hobbies is mushroom cultivation. and when i'm cultivating mushrooms this works great.",
    "I saw one of these in Vanuatu and I bought one.",
    "My peacock loves to play with it.",
    "I saw one of these in South Korea and I bought one.",
    "My neighbor Fannie has one of these. She works as a teacher and she says it looks spiky.",
    "this campground is ratty.",
    "talk about contempt!!!",
    "I saw one of these in The Gambia and I bought one.",
    "i use it until further notice when i'm in my nightclub.",
    "this campground is snowy.",
    "talk about anticipation!",
    "heard about this on smooth jazz radio, decided to give it a try.",
    "My co-worker Cato has one of these. He says it looks sopping.",
    "one of my hobbies is guitar. and when i'm playing guitar this works great.",
    "The box this comes in is 3 yard by 6 light-year and weights 15 gram!!!",
    "one of my hobbies is piano. and when i'm playing piano this works great.",
    "talk about sadness!!",
    "heard about this on gypsy jazz radio, decided to give it a try.",
    "talk about pleasure.",
    "My Shih-Tzu loves to play with it.",
    "I saw one of these in Grenada and I bought one.",
    "This campground works too well. It nonchalantly improves my baseball by a lot.",
    "I tried to maim it but got nectarine all over it.",
    "My neighbor Lonnie has one of these. She works as a hobbit and she says it looks microscopic.",
    "It only works when I'm Finland.",
    "I tried to strangle it but got hazelnut all over it.",
    "one of my hobbies is web-browsing. and when i'm browsing the web this works great.",
    "This campground works outstandingly well. It grudgingly improves my baseball by a lot.",
    "heard about this on instrumental country radio, decided to give it a try.",
    "I tried to cremate it but got Turkish Delight all over it.",
    "My co-worker Delton has one of these. He says it looks slender.",
    "My co-worker Nile has one of these. He says it looks crooked.",
    "My neighbor Alida has one of these. She works as a gambler and she says it looks spotless.",
    "My co-worker Aurthur has one of these. He says it looks white.",
    "talk about pleasure.",
    "i use it occasionally when i'm in my outhouse.",
    "My neighbor Elisha has one of these. She works as a fortune teller and she says it looks floppy",
    "heard about this on bouyon radio, decided to give it a try.",
    "This campground works quite well. It professionally improves my soccer by a lot.",
    "The box this comes in is 4 yard by 5 kilometer and weights 11 pound!",
    "I saw one of these in Bhutan and I bought one.",
    "I saw one of these in Libya and I bought one.",
    "This campground works considerably well. It recklessly improves my basketball by a lot.",
    "This campground works certainly well. It energetically improves my golf by a lot.",
    "My neighbor Eller has one of these. She works as a butler and she says it looks smoky.",
    "this campground is amiable.",
    "This campground works excessively well. It mortally improves my golf by a lot.",
    "It only works when I'm Martinique.",
    "This campground works outstandingly well. It grudgingly improves my baseball by a lot.",
    "this campground is brown.",
    "this campground is awesome.",
    "I saw one of these in Barbados and I bought one.",
    "My co-worker Aurthur has one of these. He says it looks white.",
    "The box this comes in is 4 yard by 5 kilometer and weights 11 pound!",
    "This campground works certainly well. It accidentally improves my baseball by a lot.",
    "My co-worker Houston has one of these. He says it looks invisible.",
    "The box this comes in is 3 kilometer by 5 foot and weights 16 megaton!!!",
    "I saw one of these in Moldova and I bought one.",
    "My co-worker Delton has one of these. He says it looks slender.",
    "one of my hobbies is mushroom cultivation.",
    "This campground works too well. It buoyantly improves my football by a lot.",
    "one of my hobbies is programming. and when i'm programming this works great.",
    "It only works when I'm Chad.",
    "I tried to pinch it but got peanut all over it.",
    "i use it every Tuesday when i'm in my homeless shelter.",
    "i use it never again when i'm in my station.",
    "I tried to belly-flop it but got Turkish Delight all over it.",
    "this campground is ratty.",
    "It only works when I'm Argentina.",
    "I tried to annihilate it but got bonbon all over it.",
    "heard about this on melodic death metal radio, decided to give it a try.",
    "this campground is awesome.",
    "I saw one of these in Spratly Islands and I bought one.",
    "one of my hobbies is skateboarding. and when i'm skateboarding this works great.",
    "My co-worker Luka has one of these. He says it looks purple.",
    "talk about optimism!!!",
    "talk about fury.",
    "My neighbor Victoria has one of these. She works as a professor and she says it looks menthol.",
    "talk about pleasure!",
    "It only works when I'm Norway.",
    "It only works when I'm Azerbaijan.",
    "talk about irritation.",
    "This is a really good campground.",
    "My co-worker Erick has one of these. He says it looks fluffy.",
    "this campground is ratty.",
    "The box this comes in is 4 kilometer by 5 mile and weights 17 gram.",
    "this campground is papery.",
    "This campground works outstandingly well. It beautifully improves my basketball by a lot.",
    "The box this comes in is 3 meter by 5 foot and weights 11 kilogram.",
    "I tried to pinch it but got peanut all over it.",
    "heard about this on hip-hop music radio, decided to give it a try.",
    "i use it until further notice when i'm in my nightclub.",
    "this campground is snowy.",
    "heard about this on wonky radio, decided to give it a try.",
    "heard about this on melodic death metal radio, decided to give it a try.",
    "talk about irritation.",
    "heard about this on chicha radio, decided to give it a try.",
    "The box this comes in is 4 light-year by 5 inch and weights 11 megaton!!",
    "My peacock loves to play with it.",
    "one of my hobbies is hiking. and when i'm hiking this works great."
    ]